### ISSUE TITLE
code execution backdoor

### ISSUE THREAD

**Issue by duxinglin1** [miranov25/RootInteractive#206]
We found a malicious backdoor in versions 0.0.5~0.0.19b0 of this project, and its malicious backdoor is the request package. Even if the request package was removed by pypi, many mirror sites did not completely delete this package, so it could still be installed.When using pip install RootInteractive==0.0.5 -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com, the request malicious plugin can be successfully installed.

![image](https://user-images.githubusercontent.com/58363074/172518337-982acc29-e3fa-460d-99cd-242b4ba2f3ab.png)

Repair suggestion: delete version 0.0.5~0.0.19b0 in PyPI

**Comment by miranov25** [comment]
Removing old version of RootInteractive 0.0.5-> 0.0.19b

**Comment by miranov25** [comment]
dear @duxinglin1 
The affected versions were removed from the pip. Thank you for reporting.
