### ISSUE TITLE
multi-select and select not working for float in case compression used

### ISSUE THREAD

**Issue by miranov25** [miranov25/RootInteractive#233]
Problems with the histogram range were observed with categorical variables. We assumed that the problem was related to compression for the categorical float parameters, but it was actually due to another part of the code - fixed in #234
I will ask @ehellbar, to try again after the pull request with the current master?

@Ernst, could you try to run your code with multi-select instead of the range slider?
If it is ok we can close the issue

**Comment by pl0xz0rz** [comment]
I don't really understand this. I have designed the multiselect rework to still work with compression used - as it converts the column to categorical, and compresses it losslessly. Can you reproduce the bug with them?

As for select, I am aware of it, and will work on fixing it.

**Comment by ehellbar** [comment]
Hello,
I run the code with the master today, using the multiSelect, with and without compression, for float32 and int32 variables. Everything looks fine. Thanks a lot for fixing this.
Regards,
Ernst

**Comment by miranov25** [comment]
Thank you for confirming. Closing issue #233
