### ISSUE TITLE
X, Y, errX and errY in bokehDrawArray taking tuples as input parameters

### ISSUE THREAD

**Issue by pl0xz0rz** [miranov25/RootInteractive#248]
Right now, thanks to @bulukutlu it is possible to use heatmap visualization when using the new interface by specifying "top", "bottom", "left" and "right" parameters, and setting the "visualization" parameter to "heatmap". This is already useful. I propose another interface, that would be something like

```
# Proposed interface
figureArray=[
  [[("bin_bottom_0", "bin_top_0")], [("bin_bottom_1", "bin_top_1")], {"colorZvar":["bin_count"], "source":"histogram"}]
]
```
Currently, the two options that can be used are
```
# The old interface
figureArray=[
  [[None], ["histogram"], {"visualization":"heatmap"}]
]
```
and
```
# @bulukutlu interface from #230
figureArray=[
  [[None], [None], {"visualization":"heatmap", "source":"histogram"}]
]
```
Something similar could be done to the "errX" and "errY" parameters for asymmetric error bars

**Comment by miranov25** [comment]
I agree. @bulukutlu I prefer to make this change non back compatible and use only new interface.
Do you agree?

**Comment by miranov25** [comment]
@pl0xz0rz 
For the error bars, we more or less agreed that we could use a scalar or tuple for the errors as in matplotlib
For something more sophisticated (more error bars, e.g systematic and statistical error) we can check the physics papers and ROOT implementation

**Comment by miranov25** [comment]
test in bokeh 2.2.3 is OK - merging

```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================== 36 passed, 1 skipped, 7 warnings in 1433.17s (0:23:53) ===========================================================================
```

**Comment by bulukutlu** [comment]
> I agree. @bulukutlu I prefer to make this change non back compatible and use only new interface. Do you agree?

Hi, yes this new interface looks much cleaner. We don't need back compatibility as this was used in only one dashboard so far and i can update it.
