### ISSUE TITLE
Directory named aux makes the repository impossible to clone under Windows.

### ISSUE THREAD

**Issue by pl0xz0rz** [miranov25/RootInteractive#35]
I can't use git clone to clone the repository under Windows, and when trying to unpack the archive, I get a Windows error caused by the aux directory name being invalid under Windows.

**Comment by miranov25** [comment]
Problem solved with the commit:
https://github.com/miranov25/RootInteractive/commit/1f6f812eaf7b0fbd2dfd42a23504db6d90049d96
