### ISSUE TITLE
Question regarding license

### ISSUE THREAD

**Issue by f-dangel** [miranov25/RootInteractive#70]
Hey,

I would like to try out your PyTorch [histogramdd](https://github.com/miranov25/RootInteractive/blob/master/RootInteractive/Tools/Histograms/histogramdd_pytorch.py) implementation for a research project. Unfortuntately, there's no license file in your repository which clarifies how this code may (not) be used by others (no license means [no rights for others](https://opensource.stackexchange.com/a/1721)).

Could you let me know if it's possible to copy-paste and modify the code, or if it's intentionally all rights reserved? Or will it even be available soon in PyTorch (I saw your [PR](https://github.com/pytorch/pytorch/issues/29209))?

Thanks in advance

**Comment by miranov25** [comment]
Hello.

I assume we will get soon histogramdd_pytorch.py in the PyTorch - first pull request  is already in review process https://github.com/pytorch/pytorch/pull/44485

Concerning RootInteractive license we did not have yet time to formalize project, it was no intention. We did not decide yet.
Until now we just partially implemented what is needed for our ALICE/CERN project.

We plan to prototype/refactor remaining  parts of the project (Machine learning+Analytical fits wrappers+ Interactive histogramming). The goal is to enable interactive analysis of our experimental data (see https://github.com/pytorch/pytorch/issues/29209#issuecomment-659214959)
 will discuss within ALICE/CERN what kind of license to use.

In case you do not want to wait for histogramdd in pytorch, you can copy paste implementation. 

Marian

**Comment by f-dangel** [comment]
Thank you very much for your quick answer. I'll close this issue.
